using System.Linq;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Content.Shared._FarHorizons.Vehicles.Components;
using Robust.Client.AutoGenerated;
using Content.Client._Starlight.UI;
using Content.Shared.Damage.Components;
using Robust.Shared.Timing;
using Content.Shared.PowerCell.Components;
using Content.Shared._FarHorizons.ReagentDraw.Components;
using Content.Shared.Power.Components;
using Content.Shared.Chemistry.EntitySystems;
using Content.Shared.Damage.Systems;
using Content.Shared.Power.EntitySystems;
using Robust.Shared.Containers;
using Robust.Shared.Utility;

namespace Content.Client._FarHorizons.Vehicles.Equipment;

[GenerateTypedNameReferences]
public sealed partial class VehicleEquipmentMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    private readonly SharedSolutionContainerSystem _solution;
    private readonly SharedContainerSystem _container;
    private readonly SharedBatterySystem _battery;
    private readonly DamageableSystem _damageable;
    public event Action<NetEntity, EquipmentType>? OnUninstallButtonPressed;
    private readonly Dictionary<EquipmentType, EquipmentRow> _rows = new();
    private static readonly Color _green = Color.FromHex("#00FF00");
    private static readonly Color _red = Color.FromHex("#FF0000");
    public EntityUid Entity;

    public VehicleComponent? Vehicle
    {
        get => field ?? TryGetAssignComp(_entityManager, Entity, ref field);
        set;
    } = null;

    public DamageableComponent? Damage
    {
        get => field ?? TryGetAssignComp(_entityManager, Entity, ref field);
        set;
    } = null;

    public PowerCellSlotComponent? PowerCell
    {
        get => field ?? TryGetAssignComp(_entityManager, Entity, ref field);
        set;
    } = null;

    public ReagentDrawComponent? ReagentDraw
    {
        get => field ?? TryGetAssignComp(_entityManager, Entity, ref field);
        set;
    } = null;

    public VehicleEquipmentMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _solution = _entityManager.System<SharedSolutionContainerSystem>();
        _container = _entityManager.System<SharedContainerSystem>();
        _battery = _entityManager.System<SharedBatterySystem>();
        _damageable = _entityManager.System<DamageableSystem>();
    }

    public void SetEntity(EntityUid entity)
    {
        Entity = entity;
        UpdateWindow();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateWindow();
    }

    public void UpdateWindow()
    {
        var target = Entity;
        if (!_entityManager.TryGetComponent<VehicleModsComponent>(target, out var vmComp)
        || !_entityManager.TryGetComponent<MetaDataComponent>(target, out var metaData)
        || Vehicle == null) 
            return;
        
        NameLabel.Text = metaData.EntityName;
        SpriteView.SetEntity(target);
        SpriteView.Visible = true;

        var Integrity = 0;
        if(Damage != null)
            Integrity = Math.Clamp((int) ((Vehicle.Health-_damageable.GetPositiveDamage((Entity, Damage)).DamageDict
                    .Select(p => (float)p.Value).Sum()) / Vehicle.Health * 100), 0, 100);

        var color = Color.InterpolateBetween(_red, _green, (float)Integrity / 100);

        HealthPercent.Text = $"{Integrity}%";
        HealthBar.Value = Integrity;
        HealthBar.ModulateSelfOverride = color;

        color = Color.InterpolateBetween(_red, _green, (float)GetRemainingPower(target) / 100);
        FuelLabel.Text = Vehicle.CellPowered == true ? "Power" : "Fuel"; 
        FuelPercent.Text = $"{GetRemainingPower(target)}%";
        FuelBar.Value = GetRemainingPower(target);
        FuelBar.ModulateSelfOverride = color;

        foreach (var (type, mod) in vmComp.Equipment)
        {
            if (!_rows.TryGetValue(type, out var row))
            {
                row = CreateRow(type);
                _rows[type] = row;
            }

            UpdateRow(row, type, mod);
        }
    }

    private EquipmentRow CreateRow(EquipmentType type)
    {
        var column = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(0, 10, 0, 0)
        };

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(50, 5, 0, 0)
        };

        var equipmentNameButton = new Button
        {
            HorizontalAlignment = HAlignment.Center,
            SetWidth = 300,
            Disabled = true,
        };

        var equipmentButton = new Button
        {
            SetWidth = 135,
            Disabled = true
        };

        var equipmentLabel = new RichTextLabel
        {
            Text = "Empty",
            HorizontalAlignment = HAlignment.Left
        };

        equipmentButton.AddChild(equipmentLabel);

        var uninstallButton = new Button
        {
            Text = "Uninstall",
            SetWidth = 135,
            SetHeight = 30,
            Margin = new Thickness(5, 0, 0, 0)
        };

        row.AddChildren([equipmentButton, uninstallButton]);
        column.AddChildren([equipmentNameButton, row]);

        EquipmentPanel.AddChild(column);

        var rowData = new EquipmentRow
        {
            Root = column,
            EquipmentLabel = equipmentLabel,
            UninstallButton = uninstallButton,
            EquipmentNameButton = equipmentNameButton,
            EquipmentButton = equipmentButton
        };

        uninstallButton.OnPressed += _ =>
        {
            if (rowData.CurrentMod != null)
                OnUninstallButtonPressed?.Invoke(
                    _entityManager.GetNetEntity(rowData.CurrentMod.Value),
                    type);
        };

        return rowData;
    }

    private void UpdateRow(EquipmentRow row, EquipmentType type, EntityUid? mod)
    {
        row.CurrentMod = mod;

        var equipText = "Empty";
        
        row.EquipmentNameButton.Text = type.ToString();

        if (mod != null &&
            _entityManager.TryGetComponent<DamageableComponent>(mod, out var damage) &&
            _entityManager.TryGetComponent<VehicleEquipmentComponent>(mod, out var ve))
        {
            var integrity = Math.Clamp(
                (int)((ve.Health - _damageable.GetPositiveDamage((mod.Value, damage)).DamageDict
                    .Select(p => (float)p.Value).Sum()) * 100 / ve.Health),
                0, 100);

            var color = Color.InterpolateBetween(_red, _green, integrity / 100f);

            equipText =
                $"{_entityManager.GetComponent<MetaDataComponent>(mod.Value).EntityName}: " +
                $"[color={color.ToHex()}]{integrity}%[/color]";
        }

        row.EquipmentLabel.Text = equipText;

        row.EquipmentButton.SetWidth = mod != null ? 135 : 275;

        row.UninstallButton.Visible = mod != null;
    }

    private int GetRemainingPower(EntityUid uid)
    {
        if(Vehicle == null)
            return 0;

        if(Vehicle.CellPowered)
        {
            if(PowerCell == null)
                return 0; 
            var cell = _container.GetContainer(uid, PowerCell.CellSlotId).ContainedEntities.FirstOrNull();
            if(cell == null || !_entityManager.TryGetComponent<BatteryComponent>(cell, out var batteryComp))
                return 0;
            return (int)Math.Round(_battery.GetChargeLevel((cell.Value, batteryComp)) * 100f);
        }
        else
        {
            if(ReagentDraw == null)
                return 0;
            if(!_solution.ResolveSolution(uid, ReagentDraw.SolutionContainer, ref ReagentDraw.Solution, out var solution)) 
                return 0;
            
            return (int)Math.Round(SharedSolutionContainerSystem.PercentFull(solution));
        }
    }

    private static T? TryGetAssignComp<T>(IEntityManager entSys, EntityUid ent, ref T? assign) where T : Component
    {
        if(!entSys.TryGetComponent<T>(ent, out var comp))
            return null;

        assign = comp;
        return comp;
    }
}

sealed class EquipmentRow
{
    public BoxContainer Root = default!;
    public RichTextLabel EquipmentLabel = default!;
    public Button UninstallButton = default!;
    public Button EquipmentButton = default!;
    public Button EquipmentNameButton = default!;
    public EntityUid? CurrentMod;
}