using System.Linq;
using System.Numerics;
using Content.Shared._FarHorizons.Factions;
using Content.Shared._FarHorizons.Lobby;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._FarHorizons.Lobby.UI;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class JobPicksWindow : DefaultWindow
{
    [Dependency] private readonly ISharedFactionManager _factions = default!;
    [Dependency] private readonly IPrototypeManager _protoMan = default!;
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly ISharedLobbyManager _lobby = default!;

    private readonly SpriteSystem _sprite;

    private Dictionary<ProtoId<FactionJobAssignmentPrototype>, (Label low, Label med, Label high)> _labelsCache; 

    public JobPicksWindow()
    {
        Title = Loc.GetString("job-picks-window-title");
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entMan.System<SpriteSystem>();

        _labelsCache = new();
        
        _lobby.OnJobPicksUpdated += UpdateJobList;
        BuildJobList();
        UpdateJobList();
    }

    private void UpdateJobList()
    {
        var picks = _lobby.GetJobPicks();

        foreach (var (job, (lowLabel, medLabel, highLabel)) in _labelsCache)
        {
            if (!picks.TryGetValue(job, out var value))
                value = (0, 0, 0);

            lowLabel.Text = $" {value.low}";
            medLabel.Text = $" {value.med}";
            highLabel.Text = $" {value.high}";
        }
    }

    private void BuildJobList()
    {
        _labelsCache.Clear();
        FactionTabs.RemoveAllChildren();

        foreach (var faction in _factions.ListPlayableFactions().ToList())
        {
            var factionTab = new ScrollContainer
            {
                VerticalExpand = true,
                Name = faction.Name
            };

            FactionTabs.AddChild(factionTab);

            var factionTabContent = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(0, 0, 5f, 0),
            };

            factionTab.AddChild(factionTabContent);

            var headerContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true
            };

            factionTabContent.AddChild(headerContainer);

            headerContainer.AddChild(new PanelContainer
            {
                PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#464966") },
                HorizontalExpand = true,
                Children =
                {
                    new Label
                    {
                        Margin = new Thickness(5f, 0, 0, 0),
                        Text = Loc.GetString("job-picks-window-header-job"),
                        HorizontalExpand = true
                    }
                }
            });

            headerContainer.AddChild(new PanelContainer
            {
                PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#464966") },
                Children =
                {
                    new Label
                    {
                        Margin = new Thickness(5f, 0, 0, 0),
                        Text = Loc.GetString("job-picks-window-header-low")
                    }
                }
            });

            headerContainer.AddChild(new PanelContainer
            {
                PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#464966") },
                Children =
                {
                    new Label
                    {
                        Margin = new Thickness(5f, 0, 0, 0),
                        Text = Loc.GetString("job-picks-window-header-medium")
                    }
                }
            });
            headerContainer.AddChild(new PanelContainer
            {
                PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#464966") },
                Children =
                {
                    new Label
                    {
                        Margin = new Thickness(5f, 0, 0, 0),
                        Text = Loc.GetString("job-picks-window-header-high")
                    }
                }
            });

            foreach (var jobAssignment in _factions.ListFactionJobs().Where(p => p.Faction == faction).OrderBy(p => p.Weight))
            {
                var jobContainer = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    HorizontalExpand = true
                };

                var jobIcon = _protoMan.Index(_factions.OverrideJobIcon(jobAssignment));
                var icon = new TextureRect
                {
                    TextureScale = new Vector2(2, 2),
                    VerticalAlignment = VAlignment.Center,
                    Texture = _sprite.Frame0(jobIcon.Icon)
                };

                var jobName = _factions.OverrideLocalizedJobName(jobAssignment);
                var jobLabel = new Label
                {
                    Margin = new Thickness(5f, 0, 0, 0),
                    Text = jobName,
                    HorizontalExpand = true
                };

                var lowPrioLabel = new Label
                {
                    Margin = new Thickness(5f, 0, 0, 0),
                    Text = " 0"
                };

                var mediumPrioLabel = new Label
                {
                    Margin = new Thickness(5f, 0, 0, 0),
                    Text = " 0"
                };

                var highPrioLabel = new Label
                {
                    Margin = new Thickness(5f, 0, 0, 0),
                    Text = " 0"
                };

                _labelsCache.Add(jobAssignment, (lowPrioLabel, mediumPrioLabel, highPrioLabel));

                jobContainer.AddChild(icon);
                jobContainer.AddChild(jobLabel);
                jobContainer.AddChild(lowPrioLabel);
                jobContainer.AddChild(mediumPrioLabel);
                jobContainer.AddChild(highPrioLabel);
                factionTabContent.AddChild(jobContainer);
            }
        }
    }
}