using System.Linq;
using System.Numerics;
using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared._FarHorizons.Shuttles;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Timing;

namespace Content.Client._FarHorizons.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class GunneryConsoleWindow : FancyWindow,
    IComputerWindow<NavInterfaceState>
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    private readonly SharedMapSystem _maps;
    
    public event Action<NetCoordinates, List<NetEntity>>? FireButtonPressed;
    public event Action<List<(NetEntity, bool)>>? ButtonUpdate;
    public event Action<Vector2?>? TargetMessage;

    private EntityUid? _shuttleEntity;
    public EntityUid? Entity;
    private float _accumulator = 0;
    private readonly float _threshold = 0.25f;

    private readonly List<GunneryConsoleTurretButton> _turretButtons = [];
    private List<NetEntity> _selectedTurrets = [];

    public GunneryConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _maps = _entManager.System<SharedMapSystem>();

        RadarScreen.OnRadarClick += OnFireCommand;

        SelectAllButton.OnPressed += _ => _turretButtons.ForEach(b => b.Pressed = b.Dirty = true);
        DeselectAllButton.OnPressed += _ => _turretButtons.ForEach(b => {b.Pressed = false; b.Dirty = true;});

        Startup();
    }

    public void UpdateState(NavInterfaceState scc) => RadarScreen.UpdateState(scc);

    public void Update(GunneryConsoleBuiState state)
    {
        UpdateTurretList(state.TurretEntities);
        UpdateTurretData(state.TurretEntities);
        _selectedTurrets = state.Selected;
        var updatingButtons = _turretButtons.Where(b => !b.Dirty).ToList();
        updatingButtons.ForEach(b => b.Pressed = state.Selected.Contains(b.NetEntity));
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateButtons();

        if(TargetMessage == null)
            return;

        _accumulator += args.DeltaSeconds;
        if(_accumulator >= _threshold)
        {
            _accumulator -= _threshold;
            TargetMessage.Invoke(GetMousePosition());
        }
    }

    private void UpdateButtons()
    {
        var updatedButtons = _turretButtons.Where(b => b.Dirty);
        if (!updatedButtons.Any())
            return;

        List<(NetEntity, bool)> updateList = [];
        foreach (var button in updatedButtons)
        {
            updateList.Add((button.NetEntity, button.Pressed));
            button.Dirty = false;
        }
        ButtonUpdate?.Invoke(updateList);
    }

    private void UpdateTurretList(List<GunneryConsoleTurretEntry> newTurrets)
    {
        // Turrets to be added
        var lackingTurrets = newTurrets.ExceptBy(_turretButtons.Select(t => t.NetEntity), n => n.NetEntity).ToList();
        foreach (var turret in lackingTurrets)
        {
            var button = new GunneryConsoleTurretButton(turret);
            _turretButtons.Add(button);
            GunList.AddChild(button);
        }

        // Turrets to be removed
        var excessTurrets = _turretButtons.ExceptBy(newTurrets.Select(n => n.NetEntity), t => t.NetEntity).ToList();
        foreach (var button in excessTurrets)
        {
            if (button != null)
            {
                _turretButtons.Remove(button);
                GunList.RemoveChild(button);
                _selectedTurrets.Remove(button.NetEntity);
            }
        }
    }

    private void UpdateTurretData(List<GunneryConsoleTurretEntry> turretData)
    {
        if(!_entManager.TryGetComponent<GunneryConsoleComponent>(Entity, out var comp))
            return;
        
        foreach (var button in _turretButtons)
        {
            if(!comp.TurretMetaData.TryGetValue(button.NetEntity, out var meta))
                continue;

            if (button != null)
            {
                button.Entry.MetaData = meta;
                button.UpdateAmmo(turretData.FirstOrDefault(t => t.NetEntity == button.NetEntity));
                button.UpdateText();
            }
        }

        List<(NetCoordinates, bool)> gunPositions = [];
        foreach (var button in _turretButtons.Where(b => b.Entry.MetaData?.Coordinates != null))
            gunPositions.Add(((NetCoordinates)button.Entry.MetaData?.Coordinates!, _selectedTurrets.Contains(button.NetEntity)));

        RadarScreen.SetGunPositions(gunPositions);
    }

    public void SetShuttle(EntityUid? shuttle)
    {
        _shuttleEntity = shuttle;
        RadarScreen.SetShuttle(shuttle);
    }
    
    public void SetEntity(EntityUid? entity) => Entity = entity;

    public void Startup()
    {
        if (_entManager.TryGetComponent(_shuttleEntity, out TransformComponent? shuttleXform))
        {
            SetMap(_maps.GetGridPosition((_shuttleEntity.Value, null, shuttleXform)));
        }
    }

    public void SetMap(Vector2 position)
    {
        RadarScreen.SetMap(position);
        RadarScreen.Offset = position;
    }

    private void OnFireCommand(EntityCoordinates position)
    {
        if (_selectedTurrets.Count == 0)
            return;

        FireButtonPressed?.Invoke(_entManager.GetNetCoordinates(position), _selectedTurrets);
    }

    public Vector2? GetMousePosition() => RadarScreen.GetMousePosition();

    public void TracerPing(BulletTracerPingMessage args) => RadarScreen.TracerPing(args);
}

public sealed class GunneryConsoleTurretButton : Button
{
    public NetEntity NetEntity;
    public GunneryConsoleTurretEntry Entry;
    public bool Dirty = false;

    private readonly Label _labelName = new() {HorizontalAlignment = HAlignment.Left, HorizontalExpand = true};
    private readonly Label _labelAmmo = new() {HorizontalAlignment = HAlignment.Right};

    public GunneryConsoleTurretButton(GunneryConsoleTurretEntry entry)
    {
        Entry = entry;
        NetEntity = entry.NetEntity;
        ToggleMode = true;

        FormatBox();
        UpdateText();

        OnPressed += _ => Dirty = true;
    }

    private void FormatBox()
    {
        var box = new BoxContainer {Orientation = BoxContainer.LayoutOrientation.Horizontal};
        var view = new SpriteView {Scale = new(0.5f, 0.5f)};
        view.SetEntity(NetEntity);
        box.AddChild(view);
        box.AddChild(_labelName);
        box.AddChild(_labelAmmo);
        AddChild(box);
    }

    public void UpdateText()
    {
        _labelName.Text = $"{Entry.MetaData?.EntityName ?? "Unknown Turret"}";
        _labelAmmo.Text = $"{Entry.CurrentAmmo}/{Entry.MaxAmmo}";
    }

    public void UpdateAmmo(GunneryConsoleTurretEntry entry)
    {
        Entry.CurrentAmmo = entry.CurrentAmmo;
        Entry.MaxAmmo = entry.MaxAmmo;
    }
}
