- type: job
  id: SalvageSpecialist
  name: job-name-salvagespec
  description: job-description-salvagespec
  playTimeTracker: JobSalvageSpecialist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 2.5h
  icon: "JobIconSalvageSpec" # Starlight - New distinct icon
  startingGear: SalvageSpecialistGear
  supervisors: job-supervisors-qm
  canBeAntag: false
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External
  extendedAccess:
  - Mining # Starlight
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SalvageSpecialistGear
  equipment:
    #id: SalvagePDA #Far Horizons - Disabling because you spawn with one from loadout.
    ears: ClothingHeadsetCargo
    rig: ClothingBeltSalvageWebbing #Far Horizons - They have this on top of a belt.
    belt: ClothingBeltSalvage #Far Horizons - They also get a rig now
    gloves: ClothingHandsGlovesCargo #Far Horizons
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: SalvageSpecialistChameleonOutfit
  job: SalvageSpecialist
  equipment:
    head: ClothingHeadHatCargosoft
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGasExplorer
    outerClothing: ClothingOuterWinterMiner
    belt: ClothingBeltSalvageWebbing #Far Horizons
    neck: ClothingNeckScarfStripedBrown
    gloves: ClothingHandsGlovesCargo #Far Horizons

