#region Static recipes

- type: latheRecipePack
  id: FarHorizonsSecurityGeneralEquipmentStatic
  recipes:
  - SoftPouchSecurity
  - HardPouchSecurity

# Practice ammo/mags and practice weapons
- type: latheRecipePack
  id: FarHorizonsSecurityPracticeStatic
  recipes:
  - MagazinePistol38Practice
  - MagazineBoxRevolver38Practice
  - MagazineRifle38Practice
  - SpeedLoaderRevolver38Practice
  - MagazineMagnumPractice
  - MagazineCanisterRifle556Practice
  - MagazineCanisterMagnumPractice

- type: latheRecipePack
  id: FarHorizonsSecurityAmmoStatic
  recipes:
######################CANISTER#######################
# Pistol
  - MagazineCanisterPistolRubber
  - MagazineCanisterPistolSP
  - MagazineCanisterPistolHP
  - MagazineCanisterPistolFMJ
  - MagazineCanisterPistol
# Rifle
  - MagazineCanisterRifle556Rubber
  - MagazineCanisterRifle556SP
  - MagazineCanisterRifle556HP
  - MagazineCanisterRifle556FMJ
  - MagazineCanisterRifle556
# Magnum
  - MagazineCanisterMagnumRubber
  - MagazineCanisterMagnumSP
  - MagazineCanisterMagnumHP
  - MagazineCanisterMagnumFMJ
  - MagazineCanisterMagnum
# Revolver
  - MagazineCanisterRevolver38Rubber
  - MagazineCanisterRevolver38SP
  - MagazineCanisterRevolver38HP
  - MagazineCanisterRevolver38FMJ
  - MagazineCanisterRevolver38
# Shotgun
  - MagazineCanisterShotgun12G
  - MagazineCanisterShotgun12GBuckshot
  - MagazineCanisterShotgun12GFlechette
  - MagazineCanisterShotgun12GSlug
  - MagazineCanisterShotgun12GBeanbag
  - MagazineCanisterShotgun12GPractice
  - MagazineCanisterShotgun12GFlare
######################BOX#######################
# Rifle
  - MagazineBoxRifle556Rubber
  - MagazineBoxRifle556SP
  - MagazineBoxRifle556HP
  - MagazineBoxRifle556FMJ
  - MagazineBoxRifle556
# Pistol
  - MagazineBoxPistolRubber
  - MagazineBoxPistolSP
  - MagazineBoxPistolHP
  - MagazineBoxPistolFMJ
  - MagazineBoxPistol
# Revolver
  - MagazineBoxRevolver38Rubber
  - MagazineBoxRevolver38SP
  - MagazineBoxRevolver38HP
  - MagazineBoxRevolver38FMJ
  - MagazineBoxRevolver38
# Magnum
  - MagazineBoxMagnumRubber
  - MagazineBoxMagnumSP
  - MagazineBoxMagnumHP
  - MagazineBoxMagnumFMJ
  - MagazineBoxMagnum
# Shotgun
  - BoxLethalshot
  - BoxShotgunSlug
  - BoxShellTranquilizer
  - BoxBeanbag
  - BoxShotgunFlechette
#####################MAGAZINE#######################
# Pistol
  - MagazinePistol38Rubber
  - MagazinePistolRubber
  - MagazinePistolSP
  - MagazinePistolHP
  - MagazinePistolFMJ
  - MagazinePistolEmpty
  - MagazinePistol38SP
  - MagazinePistol38HP
  - MagazinePistol38FMJ
  - MagazinePistol38Empty
# Revolver
  - SpeedLoaderRevolver38Rubber
  - SpeedLoaderRevolver38Empty
  - SpeedLoaderRevolver38SP
  - SpeedLoaderRevolver38HP
  - SpeedLoaderRevolver38FMJ
# Rifle
  - MagazineRifle38Empty 
  - MagazineRifle38SP 
  - MagazineRifle38HP 
  - MagazineRifle38FMJ 
  - MagazineRifle38Rubber
  - MagazineRifle556SP
  - MagazineRifle556HP
  - MagazineRifle556FMJ
  - MagazineRifle556Empty
# Shotgun
  - MagazineShotgunEmpty
  - MagazineShotgun
  - MagazineShotgunFlechette
  - MagazineShotgunSlug
  - MagazineShotgunBeanbag
  - MagazineShotgunPractice
  - MagazineShotgunFlare
  - SpeedLoaderMagnumBasic
  - SpeedLoaderShotgunEmpty
  - SpeedLoaderShotgunSlug
  - SpeedLoaderShotgunBeanbag
  - SpeedLoaderShotgunFlechette
  - SpeedLoaderShotgunFlare
  - SpeedLoaderShotgunPractice
# Magnum
  - MagazineMagnum
  - MagazineMagnumHP
  - MagazineMagnumFMJ
  - MagazineMagnumRubber
  - MagazineMagnumEmpty
# Magnum - Speedloader
  - SpeedLoaderMagnumEmpty
  - SpeedLoaderMagnumSP
  - SpeedLoaderMagnumHP
  - SpeedLoaderMagnumFMJ
  - SpeedLoaderMagnumRubber
# SMG
  - MagazinePistolSubMachineGunSP
  - MagazinePistolSubMachineGunHP
  - MagazinePistolSubMachineGunFMJ
  - MagazinePistolSubMachineGunEmpty
# LMG
  - Rifle556HeavyMagazinePractice
  - Rifle556HeavyMagazineRubber
  - Rifle556HeavyMagazineSP
  - Rifle556HeavyMagazineHP
  - Rifle556HeavyMagazineFMJ
  - Rifle556HeavyMagazineEmpty

#region Dynamic recipes
- type: latheRecipePack
  id: FarHorizonsSecurityWeaponsDynamic
  recipes:
  - WeaponLaserPistol
  - WeaponLaserShotgun

- type: latheRecipePack
  id: FarHorizonsSecurityThrowablesDynamic
  recipes:
  - GrenadeFlashBang
  - ClusterBangFull
  - ExGrenade
  - EmpGrenade
  - SmokeGrenade
  - TearGasGrenade
  - GrenadeStinger
  - GrenadeShrapnel

# Shared between secfab and emagged protolathe
- type: latheRecipePack
  id: FarHorizonsSecurityAmmoDynamic
  recipes:
######################CANISTER#######################
# Pistol
  - MagazineCanisterPistolIncendiary
  - MagazineCanisterPistolUranium
  - MagazineCanisterPistolAP
# Rifle
  - MagazineCanisterRifle556Incendiary
  - MagazineCanisterRifle556Uranium
  - MagazineCanisterRifle556AP
# Magnum
  - MagazineCanisterMagnumIncendiary
  - MagazineCanisterMagnumUranium
  - MagazineCanisterMagnumAP
# Revolver
  - MagazineCanisterRevolver38Incendiary
  - MagazineCanisterRevolver38Uranium
  - MagazineCanisterRevolver38AP
# Shotgun
  - MagazineCanisterShotgun12GIncendiary
  - MagazineCanisterShotgun12GUranium
  - MagazineCanisterShotgun12GUraniumFlechette
#####################BOX#######################
# Pistol
  - MagazineBoxPistolIncendiary
  - MagazineBoxPistolUranium
  - MagazineBoxPistolAP
# Revolver
  - MagazineBoxRevolver38Incendiary
  - MagazineBoxRevolver38Uranium
  - MagazineBoxRevolver38AP
# Magnum
  - MagazineBoxMagnumIncendiary
  - MagazineBoxMagnumUranium
  - MagazineBoxMagnumAP
# Rifle
  - MagazineBoxRifle556Incendiary
  - MagazineBoxRifle556Uranium
  - MagazineBoxRifle556AP
# Shotgun
  - BoxShotgunIncendiary
  - BoxShotgunUranium
  - BoxShotgunUraniumFlechette
#####################MAGAZINE#######################
# Magnum
  - MagazineMagnumIncendiary
  - MagazineMagnumUranium
  - MagazineMagnumAP
# Pistol
  - MagazinePistol38Incendiary
  - MagazinePistol38Uranium
  - MagazinePistolIncendiary
  - MagazinePistolUranium
  - MagazinePistolAP
  - MagazinePistol38AP
# Revolver
  - SpeedLoaderRevolver38Incendiary
  - SpeedLoaderRevolver38Uranium
  - SpeedLoaderRevolver38AP
# Magnum
  - SpeedLoaderMagnumIncendiary
  - SpeedLoaderMagnumUranium
  - SpeedLoaderMagnumAP
# SMG
  - MagazinePistolSubMachineGunIncendiary
  - MagazinePistolSubMachineGunUranium
  - MagazinePistolSubMachineGunAP
# Rifle
  - MagazineRifle38Incendiary 
  - MagazineRifle38Uranium  
  - MagazineRifle38AP 
  - MagazineRifle556Incendiary
  - MagazineRifle556Uranium
  - MagazineRifle556AP
# Shotgun
  - MagazineShotgunIncendiary
  - MagazineShotgunUranium
  - MagazineShotgunUraniumFlechette
  - SpeedLoaderShotgunIncendiary
  - SpeedLoaderShotgunUranium
  - SpeedLoaderShotgunUraniumFlechette
# LMG
  - Rifle556HeavyMagazineIncendiary
  - Rifle556HeavyMagazineUranium
  - Rifle556HeavyMagazineAP
# Grenade
  - MagazineGrenadeEmpty

- type: latheRecipePack
  id: FarHorizonsSecurityAmmoEmagStatic
  recipes:
# Magazine
  - L6SawMagazine
  - MagazineLightRifleSP
  - MagazineLightRifleHP
  - MagazineLightRifleFMJ
  - MagazineLightRifleMaxim
  - MagazineLightRifleEmpty
  - MagazinePistolSubMachineGunUzi
  - MagazinePistolSubMachineGunPPSH
  - MagazineMagnumRifleSP
# Box
  - MagazineBoxCaselessRifle
  - MagazineBoxCaselessRifleRubber
  - MagazineBoxCaselessRiflePractice
  - MagazineBoxLightRiflePractice

- type: latheRecipePack
  id: FarHorizonsSecurityAmmoEmagDynamic
  recipes:
# Magazine
  - MagazineLightRifleIncendiary
  - MagazineLightRifleUranium
  - MagazineLightRifleAP

- type: latheRecipePack
  id: FarHorizonsSecurityVehiclePartsDynamic
  recipes:
  - LightArmorKit
  - SecSiren