using System.Linq;
using System.Numerics;
using Content.Client.CrewManifest;
using Content.Client.GameTicking.Managers;
using Content.Client.UserInterface.Controls;
using Content.Client.Players.PlayTimeTracking;
using Content.Shared.CCVar;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.BoxContainer;
using Content.Shared._FarHorizons.Factions;
using Robust.Client.Graphics;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LateJoinGui : DefaultWindow
    {
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        [Dependency] private readonly IConfigurationManager _configManager = default!;
        [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
        [Dependency] private readonly JobRequirementsManager _jobRequirements = default!;
        [Dependency] private readonly IClientPreferencesManager _preferencesManager = default!;
        [Dependency] private readonly ILogManager _logManager = default!;
        [Dependency] private readonly ISharedFactionManager _factions = default!; // Far Horizons

        /// <summary>
        /// Action invoked when a job is pressed
        /// </summary>
        public event Action<(NetEntity, int, (ProtoId<FactionPrototype> faction, ProtoId<JobPrototype> job))> SelectedId;

        private readonly ClientGameTicker _gameTicker;
        private readonly SpriteSystem _sprites;
        private readonly CrewManifestSystem _crewManifest;
        private readonly ISawmill _sawmill;

        // Far Horizons
        private readonly Dictionary<NetEntity, Dictionary<(ProtoId<FactionPrototype> faction, ProtoId<JobPrototype> job), List<JobButton>>> _jobButtons = new();
        private readonly Dictionary<NetEntity, Dictionary<(ProtoId<FactionPrototype> faction, ProtoId<DepartmentPrototype> job), BoxContainer>> _jobCategories = new();
        Dictionary<ProtoId<FactionPrototype>, BoxContainer> _factionTabs = new();

        private int? _selectedSlot;
        
        public BoxContainer CharList => CharacterList;

        public LateJoinGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _sprites = _entitySystem.GetEntitySystem<SpriteSystem>();
            _crewManifest = _entitySystem.GetEntitySystem<CrewManifestSystem>();
            _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();
            _sawmill = _logManager.GetSawmill("latejoin.panel");

            _jobRequirements.Updated += RebuildUI;
            RebuildUI();

            SelectedId += x =>
            {
                var (station, slot, jobId) = x;
                if (slot < 0)
                    return;
                _sawmill.Info($"Late joining as ID: {jobId}");
                _consoleHost.ExecuteCommand($"joingame {slot} {CommandParsing.Escape(jobId.faction)} {CommandParsing.Escape(jobId.job)} {station}");
                Close();
            };

            _gameTicker.LobbyJobsAvailableUpdated += JobsAvailableUpdated;
        }

        /// <summary>
        /// Rebuild all of the character picker buttons
        /// </summary>
        private void RebuildCharacterList()
        {
            CharacterList.RemoveAllChildren();

            var group = new ButtonGroup();
            var first = !_selectedSlot.HasValue;
            foreach (var (slot, profile) in _preferencesManager.Preferences!.Characters)
            {
                var isSelected = _selectedSlot.HasValue ? slot == _selectedSlot : first;
                if (profile is not HumanoidCharacterProfile humanoid)
                    continue;
                var characterPickerButton =
                    new CharacterPickerButton(group, humanoid, isSelected, true); // Far Horizons
                CharacterList.AddChild(characterPickerButton);

                if (isSelected && _selectedSlot != slot)
                {
                    _selectedSlot = slot;
                    RebuildJobList();
                }

                characterPickerButton.OnPressed += _ =>
                {
                    _selectedSlot = slot;
                    RebuildJobList();
                };
                if(first)
                    first = false;
            }
        }

        private void RebuildJobList()
        {
            JobList.RemoveAllChildren();
            _jobButtons.Clear();
            _jobCategories.Clear();

            if (_gameTicker is { DisallowedLateJoin: false, StationNames.Count: 0 })
                _sawmill.Warning("No stations exist, nothing to display in late-join GUI");

            if (!_selectedSlot.HasValue ||
                !_preferencesManager.Preferences!.TryGetHumanoidInSlot(_selectedSlot.Value, out var humanoid))
                return;

            foreach (var (id, name) in _gameTicker.StationNames)
            {
                JobList.AddChild(new StripeBack()
                {
                    Children =
                    {
                        new PanelContainer()
                        {
                            Children =
                            {
                                new Label()
                                {
                                    StyleClasses = { "LabelBig" },
                                    Text = name,
                                    Align = Label.AlignMode.Center,
                                }
                            }
                        }
                    }
                });

                if (_configManager.GetCVar(CCVars.CrewManifestWithoutEntity))
                {
                    var crewManifestButton = new Button()
                    {
                        Text = Loc.GetString("crew-manifest-button-label")
                    };
                    crewManifestButton.OnPressed += _ => _crewManifest.RequestCrewManifest(id);

                    JobList.AddChild(crewManifestButton);
                }

                // Far Horizons factions
                var faction_tab_container = new TabContainer
                {
                    VerticalExpand = true
                };
                JobList.AddChild(faction_tab_container);

                Dictionary<ProtoId<FactionPrototype>, Control> faction_tabs = [];

                foreach (var faction in _factions.ListSpawnableFactions().ToList()){
                    var faction_tab = new ScrollContainer
                    {
                        VerticalExpand = true,
                        Name = faction.Name,
                        ToolTip = Loc.GetString(faction.Description)
                    };

                    faction_tab_container.AddChild(faction_tab);

                    var faction_tab_content = new BoxContainer
                    {
                        Orientation = LayoutOrientation.Vertical,
                        Margin = new Thickness(0, 0, 5f, 0),
                    };

                    faction_tab.AddChild(faction_tab_content);

                    faction_tabs.Add(faction, faction_tab_content);
                }

                _jobButtons[id] = [];

                foreach (var dptAssignment in _factions.ListFactionDepartments().Where(p => _factions.ListSpawnableFactionIDs().Contains(p.Faction)))
                {
                    if (!_prototypeManager.TryIndex<DepartmentPrototype>(dptAssignment.Department, out var department) ||
                        !_prototypeManager.TryIndex<FactionPrototype>(dptAssignment.Faction, out var faction))
                        continue;

                    var departmentName = Loc.GetString(department.Name);
                    _jobCategories[id] = [];
                    var stationAvailable = _gameTicker.JobsAvailable[id];
                    var jobsAvailable = department.Roles
                                        .Where(stationAvailable.ContainsKey)
                                        .Select(_prototypeManager.Index<JobPrototype>)
                                        .ToList();

                    // Do not display departments with no jobs available.
                    if (jobsAvailable.Count == 0)
                        continue;

                    if (!_jobCategories[id].TryGetValue(((ProtoId<FactionPrototype>)faction.ID, (ProtoId<DepartmentPrototype>)department.ID), out var category))
                    {
                        category = new BoxContainer
                        {
                            Orientation = LayoutOrientation.Vertical,
                            Name = department.ID,
                        };

                        category.AddChild(new PanelContainer
                        {
                            PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#464966") },
                            Children =
                            {
                                new Label
                                {
                                    Text = Loc.GetString("humanoid-profile-editor-department-jobs-label",
                                        ("departmentName", departmentName)),
                                    Margin = new Thickness(5f, 0, 0, 0)
                                }
                            }
                        });

                        _jobCategories[id][(faction.ID, department.ID)] = category;
                        faction_tabs[faction].AddChild(category);
                    }

                    foreach (var jobAssignment in _factions.ListFactionJobs()
                                                .Where(p => (p.Faction == faction) &&
                                                            department.Roles.Contains(p.Job) &&
                                                            jobsAvailable.Any(e => e.ID == p.Job) &&
                                                            stationAvailable.ContainsKey(p.Job)))
                    {
                        if (!_prototypeManager.TryIndex<JobPrototype>(jobAssignment.Job, out var job))
                            continue;
                        
                        var value = stationAvailable[jobAssignment.Job];

                        var jobLabel = new Label
                        {
                            Margin = new Thickness(5f, 0, 0, 0)
                        };

                        var jobButton = new JobButton(jobLabel, jobAssignment.Faction, jobAssignment.Job, _factions.OverrideLocalizedJobName(jobAssignment), value);

                        var jobSelector = new BoxContainer
                        {
                            Orientation = LayoutOrientation.Horizontal,
                            HorizontalExpand = true
                        };

                        var icon = new TextureRect
                        {
                            TextureScale = new Vector2(2, 2),
                            VerticalAlignment = VAlignment.Center
                        };

                        var jobIcon = _prototypeManager.Index(_factions.OverrideJobIcon(jobAssignment));
                        icon.Texture = _sprites.Frame0(jobIcon.Icon);
                        jobSelector.AddChild(icon);

                        jobSelector.AddChild(jobLabel);
                        jobButton.AddChild(jobSelector);
                        category.AddChild(jobButton);

                        // just send a -1 if there is no selected slot... catch it later
                        jobButton.OnPressed += _ => SelectedId.Invoke((id, _selectedSlot ?? -1, (jobButton.FactionId, jobButton.JobId)));

                        if (!_jobRequirements.IsAllowed(job, humanoid, out var reason))
                        {
                            jobButton.Disabled = true;

                            if (!reason.IsEmpty)
                            {
                                var tooltip = new Tooltip();
                                tooltip.SetMessage(reason);
                                jobButton.TooltipSupplier = _ => tooltip;
                            }

                            jobSelector.AddChild(new TextureRect
                            {
                                TextureScale = new Vector2(0.4f, 0.4f),
                                Stretch = TextureRect.StretchMode.KeepCentered,
                                Texture = _sprites.Frame0(new SpriteSpecifier.Texture(new ("/Textures/Interface/Nano/lock.svg.192dpi.png"))),
                                HorizontalExpand = true,
                                HorizontalAlignment = HAlignment.Right,
                            });
                        }
                        else if (value == 0)
                        {
                            jobButton.Disabled = true;
                        }

                        if (!_jobButtons[id].ContainsKey((faction, job)))
                        {
                            _jobButtons[id][(faction, job)] = new List<JobButton>();
                        }

                        _jobButtons[id][(faction, job)].Add(jobButton);
                    }

                    faction_tabs[dptAssignment.Faction].AddChild(new Control
                    {
                        MinSize = new Vector2(0, 23),
                    });
                }
            }
        }

        private void RebuildUI()
        {
            RebuildCharacterList();
            RebuildJobList();
        }

        private void JobsAvailableUpdated(IReadOnlyDictionary<NetEntity, Dictionary<ProtoId<JobPrototype>, int?>> updatedJobs)
        {
            foreach (var stationEntries in updatedJobs)
            {
                if (_jobButtons.ContainsKey(stationEntries.Key))
                {
                    var jobsAvailable = stationEntries.Value;

                    var existingJobEntries = _jobButtons[stationEntries.Key];
                    foreach (var existingJobEntry in existingJobEntries)
                    {
                        if (jobsAvailable.ContainsKey(existingJobEntry.Key.job))
                        {
                            var updatedJobValue = jobsAvailable[existingJobEntry.Key.job];
                            foreach (var matchingJobButton in existingJobEntry.Value)
                            {
                                if (matchingJobButton.Amount != updatedJobValue)
                                {
                                    matchingJobButton.RefreshLabel(updatedJobValue);
                                    matchingJobButton.Disabled |= matchingJobButton.Amount == 0;
                                }
                            }
                        }
                    }
                }
            }
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            if (disposing)
            {
                _jobRequirements.Updated -= RebuildUI;
                _gameTicker.LobbyJobsAvailableUpdated -= JobsAvailableUpdated;
                _jobButtons.Clear();
            }
        }
    }

    sealed class JobButton : ContainerButton
    {
        public Label JobLabel { get; }
        public ProtoId<FactionPrototype> FactionId { get; } // Far Horizons
        public ProtoId<JobPrototype> JobId { get; }
        public string JobLocalisedName { get; }
        public int? Amount { get; private set; }
        private bool _initialised = false;

        public JobButton(Label jobLabel, ProtoId<FactionPrototype> factionID, ProtoId<JobPrototype> jobId, string jobLocalisedName, int? amount)
        {
            JobLabel = jobLabel;
            FactionId = factionID;
            JobId = jobId;
            JobLocalisedName = jobLocalisedName;
            RefreshLabel(amount);
            AddStyleClass(StyleClassButton);
            _initialised = true;
        }

        public void RefreshLabel(int? amount)
        {
            if (Amount == amount && _initialised)
            {
                return;
            }
            Amount = amount;

            JobLabel.Text = Amount != null ?
                Loc.GetString("late-join-gui-job-slot-capped", ("jobName", JobLocalisedName), ("amount", Amount)) :
                Loc.GetString("late-join-gui-job-slot-uncapped", ("jobName", JobLocalisedName));
        }
    }
}
