using System.Linq;
using System.Numerics;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using Robust.Shared.Prototypes;

namespace Content.Client._FarHorizons.Administration.UI.SetMindJob;

[GenerateTypedNameReferences]
public sealed partial class SetMindJobMenu : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IClientConsoleHost _consoleHost = default!;

    public NetUserId? TargetEntityId { get; set; }
    private JobPrototype? _selectedJob;

    public SetMindJobMenu()
    {
        MinSize = SetSize = new Vector2(250, 320);
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Title = Loc.GetString("set-mind-job-menu-title");

        ConfirmButton.Text = Loc.GetString("set-mind-job-menu-confirm-button");
        ConfirmButton.OnPressed += ConfirmButtonOnOnPressed;
        SearchBar.OnTextChanged += SearchBarOnOnTextChanged;
        JobsList.OnItemSelected += JobListOnOnItemSelected;
        JobsList.OnItemDeselected += JobListOnOnItemDeselected;
        PopulateList();
    }

    private void ConfirmButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        if (TargetEntityId == null || _selectedJob == null)
            return;
        var command = $"setmindjob {TargetEntityId} {_selectedJob.ID}";
        _consoleHost.ExecuteCommand(command);
        Close();
    }

    private void JobListOnOnItemSelected(ItemList.ItemListSelectedEventArgs obj)
    {
        _selectedJob = (JobPrototype) obj.ItemList[obj.ItemIndex].Metadata!;
        ConfirmButton.Disabled = false;
    }

    private void JobListOnOnItemDeselected(ItemList.ItemListDeselectedEventArgs obj)
    {
        _selectedJob = null;
        ConfirmButton.Disabled = true;
    }


    private void SearchBarOnOnTextChanged(LineEdit.LineEditEventArgs obj)
    {
        PopulateByFilter(SearchBar.Text);
    }

    private IEnumerable<JobPrototype> GetPrototypes() => _prototypeManager.EnumeratePrototypes<JobPrototype>();

    private void PopulateList()
    {
        foreach (var job in GetPrototypes())
        {
            JobsList.Add(GetItem(job, JobsList));
        }
    }

    private void PopulateByFilter(string filter)
    {
        JobsList.Clear();
        foreach (var job in GetPrototypes())
        {
            if (!string.IsNullOrEmpty(filter) &&
                job.ID.ToLowerInvariant().Contains(filter.Trim().ToLowerInvariant()))
            {
                JobsList.Add(GetItem(job, JobsList));
            }
        }
    }

    private static ItemList.Item GetItem(JobPrototype job, ItemList itemList)
    {
        return new(itemList)
        {
            Metadata = job,
            Text = job.ID
        };
    }
}
