using System.Linq;
using System.Numerics;
using Content.Client._FarHorizons.Humanoid.UI.Helpers;
using Content.Client._FarHorizons.LimbDamage.UI;
using Content.Shared._FarHorizons.Humanoid;
using Content.Shared._FarHorizons.LimbDamage.Components;
using Content.Shared.Body;
using Content.Shared.Humanoid.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._FarHorizons.Humanoid.UI;

[GenerateTypedNameReferences]
public sealed partial class CyberneticsPicker : Control
{
    [Dependency] private readonly IPrototypeManager _protoMan = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IResourceCache _resCahce = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    private readonly SpriteSystem _sprite;

    private readonly List<CyberneticImplant> _allCyberware; 
    private List<CyberneticImplant> _installedCyberware = [];
    private readonly Dictionary<string, SpriteSpecifier.Rsi> _icons;

    public string FontPath = "/Fonts/_FarHorizons/VT323/vt323-latin-400-normal.ttf";
    private readonly FontResource _font;

    public Action<List<CyberneticImplant>>? OnCyberneticsUpdated;
    private int _pointCapacity;
    private int _currentPoints => 
        _installedCyberware.Sum(part => part.Cost);

    private ProtoId<LimbTargettingPrototype>? _limbTarget;

    private Vector2 _currentMousePosition => 
        (UserInterfaceManager.MousePositionScaled.Position * UIScale) - GlobalPixelPosition;
    private ProtoId<OrganCategoryPrototype>? _hovered;
    private ProtoId<OrganCategoryPrototype>? _expandedButton;
    private List<ExpandableButton> _buttons = new();
    private List<CyberneticSelectorConnectingLine> _lines = new();
    private Tooltip? _tooltip;

    private static Dictionary<ProtoId<OrganCategoryPrototype>, float> _emptyHighlight = new()
        {
            {"Head", 0},
            {"Torso", 0},

            {"ArmRight", 0},
            {"HandRight", 0},
            {"LegRight", 0},
            {"FootRight", 0},

            {"ArmLeft", 0},
            {"HandLeft", 0},
            {"LegLeft", 0},
            {"FootLeft", 0},
        };

    private static readonly Dictionary<ProtoId<OrganCategoryPrototype>, (Vector2, bool, ProtoId<OrganCategoryPrototype>?)> _buttonLocations = new()
    {
        {"EyeImplant", (new Vector2(-110, 20), false, null)},
        {"Eyes", (new Vector2(-50, 20), false, "Head")},
        {"ArmRight", (new Vector2(-50, 80), false, "ArmRight")},
        {"HandRight", (new Vector2(-50, 140), false, "HandRight")},
        {"LegRight", (new Vector2(-50, 200), false, "LegRight")},
        {"FootRight", (new Vector2(-50, 260), false, "FootRight")},

        {"BrainImplant", (new Vector2(200, 20), true, "Head")},
        {"ArmLeft", (new Vector2(200, 80), true, "ArmLeft")},
        {"HandLeft", (new Vector2(200, 140), true, "HandLeft")},
        {"LegLeft", (new Vector2(200, 200), true, "LegLeft")},
        {"FootLeft", (new Vector2(200, 260), true, "FootLeft")},
    };

    private static float _buttonSize = 40;

    public CyberneticsPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entityManager.System<SpriteSystem>();

        _allCyberware = CyberneticImplant.GetAllCybernetics(_protoMan);
        _icons = GetIconsList();

        _font = _resCahce.GetResource<FontResource>(FontPath);

        PopulateUI();
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        _hovered = GetHovered() ?? LimbTargettingDisplay.GetHighlight();
        if (_hovered != null && !_buttonLocations.Keys.Contains(_hovered.Value))
            _hovered = null;
        
        DrawLines(handle);
        DrawButtons(handle);
        DrawTooltip(handle);

        UpdateLimbColors();
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (args.Handled || args.Function != EngineKeyFunctions.UIClick)
            return;

        if (_expandedButton == null && _hovered != null)
            _expandedButton = _hovered;
        else
        {
            var matching = _buttons.Where(p => p.Expanded).ToList();
            if (matching.Count <= 0)
                return;

            if (matching.First().IsExpandedHovering())
            {
                matching.First().ProcessClick();
                return;
            }
            
            _expandedButton = null;
        }
    }

    private void DrawLines(DrawingHandleScreen handle)
    {
        foreach (var line in _lines)
            line
                .WithBasePosition(BackgroundPanel.Position)
                .WithLimbUiScale(new Vector2(BackgroundPanel.Width, BackgroundPanel.Height))
                .Draw(handle, UIScale);
    }

    private void DrawButtons(DrawingHandleScreen handle)
    {
        foreach (var button in _buttons)
        {
            button.WithBasePosition(BackgroundPanel.Position);
            button.WithHovered(_hovered);
            button.WithExpanded(_expandedButton);
            if (!button.Expanded)
                button.Draw(handle, UIScale);
        }

        var expandedButton = _buttons.Where(p => p.Expanded).FirstOrDefault((ExpandableButton?)null);
        expandedButton?.UpdateHovering(_currentMousePosition, UIScale);
        expandedButton?
            .Draw(handle, UIScale);
    }

    private void DrawTooltip(DrawingHandleScreen handle)
    {
        if (_tooltip == null)
            return;
        
        _tooltip.WithMousePosition(_currentMousePosition);
        _tooltip.WithCurrentShown(GetHoveredItem());
        _tooltip.Draw(handle, UIScale);
    }

    private string? GetHoveredItem()
    {
        var targetButton = _expandedButton ?? _hovered;
        if (targetButton == null)
            return null;

        var buttons = _buttons.Where(p => p.Id == targetButton).ToList();
        if (buttons.Count <= 0)
            return null;

        var button = buttons.First();
        _tooltip?.WithSide(button.Side); // Why is this here? Shut up.
        return !button.Expanded ? button.GetSelection() : button.GetHovered();
    }

    private void UpdateLimbColors()
    {
        LimbTargettingDisplay.LimbDamage = _emptyHighlight.ShallowClone();

        var highlighted = _expandedButton ?? _hovered;

        if (highlighted == null)
            return;

        LimbTargettingDisplay.LimbDamage[highlighted.Value] = 200f;
    }

    // On any state update full state is sent and entire UI is rebuilt
    public void SetData(List<string> cyberneticIds, SpeciesPrototype species, int pointCapacity)
    {
        _installedCyberware = _allCyberware.Where(p => cyberneticIds.Contains(p.Id)).ToList();
        _pointCapacity = pointCapacity;
        _limbTarget = GetLimbTargetting(species);

        PopulateUI();
    }

    private ProtoId<LimbTargettingPrototype>? GetLimbTargetting(SpeciesPrototype species)
    {
        if (!_protoMan.TryIndex(species.Prototype, out var speciesEnt) ||
            !speciesEnt.Components.TryGetComponent("LimbDamageable", out var limbDamageableComp) ||
            limbDamageableComp is not LimbDamageableComponent limbDamageable)
            return null;

        return limbDamageable.Proto;
    }

    private Dictionary<string, SpriteSpecifier.Rsi> GetIconsList() =>
        _allCyberware.ToDictionary(
            p => p.Id,
            p =>
            {
                if (_protoMan.Index(p.Id).Components.TryGetValue("Sprite", out var sprite) &&
                    sprite.Component is SpriteComponent { BaseRSI: not null } spriteComp &&
                    spriteComp.AllLayers.Any() &&
                    spriteComp.AllLayers.First().ActualRsi != null)
                    return new SpriteSpecifier.Rsi(spriteComp.AllLayers.First().ActualRsi!.Path, spriteComp.AllLayers.First().RsiState.Name ?? "");

                return new SpriteSpecifier.Rsi(new ResPath("Objects/Fun/bikehorn.rsi"), "icon");
            }
        );

    // Installs parts, also installs attached parts
    private void InstallPart(CyberneticImplant part)
    {
        if (_installedCyberware.FirstOrNull(p => p.Slot == part.Slot) is { } existingPart)
            _installedCyberware.Remove(existingPart);

        _installedCyberware.Add(part);
        foreach (var attachedImplant in part.AttachedParts
                     .Select(attachedPart => _allCyberware.Where(p => p.Id == attachedPart)
                         .FirstOrDefault(new CyberneticImplant { Id = "broken" }))
                     .Where(attachedImplant => attachedImplant.Id != "broken")) InstallPart(attachedImplant);
    }

    // Removes parts, but not if it's a part that was attached by other part
    private void RemovePart(CyberneticImplant part)
    {
        if (_installedCyberware.Any(p => p.AttachedParts.Contains(part.Id)))
            return;

        _installedCyberware.Remove(part);

        foreach (var attachedImplant in part.AttachedParts
                     .Select(attachedPart => _allCyberware.Where(p => p.Id == attachedPart)
                         .FirstOrDefault(new CyberneticImplant { Id = "broken" }))
                     .Where(attachedImplant => attachedImplant.Id != "broken")) RemovePart(attachedImplant);
    }

    private int CalculateCost(CyberneticImplant part) =>
        part.Cost + part.AttachedParts
            .Select(attachedPart => _allCyberware.Where(p => p.Id == attachedPart)
                .FirstOrDefault(new CyberneticImplant { Id = "broken" }))
            .Where(attachedImplant => attachedImplant.Id != "broken")
            .Sum(CalculateCost);

    // Install button clicked, install selected part
    private void InstallCybernetics(string id)
    {
        if (_allCyberware.Where(p => p.Id == id).FirstOrNull() is not {} selectedImplant)
            return;
        
        if (_currentPoints + CalculateCost(selectedImplant) <= _pointCapacity)
            InstallPart(selectedImplant);
        
        PopulateUI();
        OnCyberneticsUpdated?.Invoke(_installedCyberware);
    }

    // Remove button clicked, remove selected part
    private void RemoveCybernetics(string id)
    {
        if (_allCyberware.Where(p => p.Id == id).FirstOrNull() is not {} selectedImplant)
            return;

        RemovePart(selectedImplant);
        PopulateUI();
        OnCyberneticsUpdated?.Invoke(_installedCyberware);
    }

    private void UpdateSelection()
    {
        foreach (var button in _buttons)
            foreach (var installed in _installedCyberware)
                button.SetSelection(installed.Id);
    }

    private void UpdateBaseColors()
    {
        _emptyHighlight = new Dictionary<ProtoId<OrganCategoryPrototype>, float>
        {
            {"Head", 0},
            {"Torso", 0},

            {"ArmRight", 0},
            {"HandRight", 0},
            {"LegRight", 0},
            {"FootRight", 0},

            {"ArmLeft", 0},
            {"HandLeft", 0},
            {"LegLeft", 0},
            {"FootLeft", 0},
        };

        foreach (var implant in _installedCyberware)
            if (implant.Slot != null && _emptyHighlight.ContainsKey(implant.Slot.Value))
                _emptyHighlight[implant.Slot.Value] = 40f;
                
    }

    private void ToggleSelection(ProtoId<OrganCategoryPrototype> target)
    {
        if (_expandedButton == null)
            _expandedButton = _buttonLocations.Keys.Contains(target) ? target : (ProtoId<OrganCategoryPrototype>?)null;
        else
            _expandedButton = null;
    }

    private void ToggleChanged((string? oldV, string? newV) value)
    {
        if (value.newV == null && value.oldV != null)
            RemoveCybernetics(value.oldV);
        else if (value.newV != null)
            InstallCybernetics(value.newV);

        _expandedButton = null;
    }

    // Build full UI from scratch
    private void PopulateUI()
    {
        var targetProto = _protoMan.Index(_limbTarget ?? "LimbTargetHuman");

        LimbTargettingDisplay.DrawLimbs =
            targetProto.Limbs.ToDictionary(p => p.Limb, p => new DrawLimb(_sprite, p.Area, p.Sprites));

        LimbTargettingDisplay.DefaultColor = Vector3.One;
        LimbTargettingDisplay.HighlightColor = new Vector3(1f, 0.85f, 0f);

        LimbTargettingDisplay.WithHealth = true;
        LimbTargettingDisplay.FullHealthColor = Vector3.One;
        LimbTargettingDisplay.DamagedHealthColor = new Vector3(0f, 0.5f, 1f);
        LimbTargettingDisplay.BadlyDamagedHealthColor = new Vector3(1f, 0.85f, 0f);
        LimbTargettingDisplay.LimbDamage = _emptyHighlight;
        LimbTargettingDisplay.UpdateSelection(null);

        LimbTargettingDisplay.InitShaders(_protoMan);
        LimbTargettingDisplay.OnSelectedLimb ??= ToggleSelection;

        _buttons = new();
        _lines = new();

        foreach (var (limb, (location, side, lineTarget)) in _buttonLocations)
        {
            var button = new ExpandableButton(_timing, limb, Vector2.One * _buttonSize, location, side);
            var cybernetics = _allCyberware.Where(p => p.Slot == limb);
            List<SubButtonElement> elements = new();
            foreach (var cybernetic in cybernetics)
                if (_icons.TryGetValue(cybernetic.Id, out var icon))
                    elements.Add(new SubButtonElement(cybernetic.Id, _sprite.Frame0(icon), cybernetic.IconScale, cybernetic.IconOffset));

            button.SetupSubButtons(elements);
            button.SelectionChanged ??= ToggleChanged;
            button.CloseRequest ??= _ => _expandedButton = null;
            _buttons.Add(button);

            var limbLayer = targetProto.Limbs.FirstOrDefault(p => p.Limb == lineTarget);

            if (limbLayer == null)
                continue;
            
            var line = new CyberneticSelectorConnectingLine(limbLayer.Area, Vector2.One * _buttonSize, location, side);
            _lines.Add(line);
        }

        var tooltips =
            _allCyberware.ToDictionary(p => p.Id,
                p => new TooltipContent(p.Name, Loc.GetString("roundstart-cybernetics-cost", ("cost", p.Cost)),
                    p.Description, p.Cost > 0));
        _tooltip = new Tooltip(tooltips, _font);
        UpdateSelection();
        UpdateBaseColors();

        CyberneticsPoints.Text = Loc.GetString("cybernetics-points-remaining", ("points", _pointCapacity - _currentPoints), ("points_total", _pointCapacity));
    }

    private ProtoId<OrganCategoryPrototype>? GetHovered()
    {
        var hovered = _buttons
        .Where(p => p.IsHovering(_currentMousePosition, UIScale))
        .Select(p => p.Id)
        .ToList();

        return hovered.Count > 0 ? hovered.First() : (ProtoId<OrganCategoryPrototype>?)null;
    }
}
