#region NanoTrasen

- type: entity
  id: LockerSecurityFHFilled
  suffix: NT, Filled
  parent: LockerSecurityFH
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      - id: WeaponDisabler
      - id: ClothingUniformJumpsuitSecGrey
        prob: 0.3
      - id: ClothingHeadHelmetBasic
      - id: ClothingOuterArmorBasic
      - id: ClothingBeltSecurityFilled
      - id: Flash
      - id: ClothingEyesGlassesSecurity
      - id: ClothingEyesHudSecurity
      - id: ClothingHeadsetSecurity
      - id: ClothingHandsGlovesSecurityRed
      - id: ClothingShoesBootsJack
      - id: WeaponMeleeNeedle
      - id: HoloprojectorSecurity
      - id: BookSpaceLaw
  
- type: entity
  id: LockerSecurityLargeFHFilled
  suffix: NT, Filled
  parent: LockerSecurityLargeFH
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        amount: 2
      - id: WeaponDisabler
        amount: 2
      - id: ClothingUniformJumpsuitSecGrey
        prob: 0.6
      - id: ClothingHeadHelmetBasic
        amount: 2
      - id: ClothingOuterArmorBasic
        amount: 2
      - id: ClothingBeltSecurityFilled
        amount: 2
      - id: Flash
        amount: 2
      - id: ClothingEyesGlassesSecurity
        amount: 2
      - id: ClothingEyesHudSecurity
        amount: 2
      - id: ClothingHeadsetSecurity
        amount: 2
      - id: ClothingHandsGlovesSecurityRed
        amount: 2
      - id: ClothingShoesBootsJack
        amount: 2
      - id: WeaponMeleeNeedle
      - id: HoloprojectorSecurity
        amount: 2
      - id: BookSpaceLaw
        amount: 2

- type: entity
  id: LockerSecurityLargeFHLFilled
  suffix: NT, Filled, Left
  parent: LockerSecurityLargeFHL
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        amount: 2
      - id: WeaponDisabler
        amount: 2
      - id: ClothingUniformJumpsuitSecGrey
        prob: 0.6
      - id: ClothingHeadHelmetBasic
        amount: 2
      - id: ClothingOuterArmorBasic
        amount: 2
      - id: ClothingBeltSecurityFilled
        amount: 2
      - id: Flash
        amount: 2
      - id: ClothingEyesGlassesSecurity
        amount: 2
      - id: ClothingEyesHudSecurity
        amount: 2
      - id: ClothingHeadsetSecurity
        amount: 2
      - id: ClothingHandsGlovesSecurityRed
        amount: 2
      - id: ClothingShoesBootsJack
        amount: 2
      - id: WeaponMeleeNeedle
      - id: HoloprojectorSecurity
        amount: 2
      - id: BookSpaceLaw
        amount: 2

- type: entity
  id: LockerSecurityLargeFHMFilled
  suffix: NT, Filled, Middle
  parent: LockerSecurityLargeFHM
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        amount: 3
      - id: WeaponDisabler
        amount: 3
      - id: ClothingUniformJumpsuitSecGrey
        prob: 0.9
      - id: ClothingHeadHelmetBasic
        amount: 3
      - id: ClothingOuterArmorBasic
        amount: 3
      - id: ClothingBeltSecurityFilled
        amount: 3
      - id: Flash
        amount: 3
      - id: ClothingEyesGlassesSecurity
        amount: 3
      - id: ClothingEyesHudSecurity
        amount: 3
      - id: ClothingHeadsetSecurity
        amount: 3
      - id: ClothingHandsGlovesSecurityRed
        amount: 3
      - id: ClothingShoesBootsJack
        amount: 3
      - id: WeaponMeleeNeedle
      - id: HoloprojectorSecurity
        amount: 3
      - id: BookSpaceLaw
        amount: 3

- type: entity
  id: LockerSecurityLargeFHRFilled
  suffix: NT, Filled, Right
  parent: LockerSecurityLargeFHR
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        amount: 2
      - id: WeaponDisabler
        amount: 2
      - id: ClothingUniformJumpsuitSecGrey
        prob: 0.6
      - id: ClothingHeadHelmetBasic
        amount: 2
      - id: ClothingOuterArmorBasic
        amount: 2
      - id: ClothingBeltSecurityFilled
        amount: 2
      - id: Flash
        amount: 2
      - id: ClothingEyesGlassesSecurity
        amount: 2
      - id: ClothingEyesHudSecurity
        amount: 2
      - id: ClothingHeadsetSecurity
        amount: 2
      - id: ClothingHandsGlovesSecurityRed
        amount: 2
      - id: ClothingShoesBootsJack
        amount: 2
      - id: WeaponMeleeNeedle
      - id: HoloprojectorSecurity
        amount: 2
      - id: BookSpaceLaw
        amount: 2

- type: entity
  id: LockerWardenFHFilled
  suffix: NT, Filled
  parent: LockerWardenFH
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      - id: WeaponEnergyShotgun
      - id: WeaponDisabler
      - id: ClothingBeltSecurityFilled
      - id: Flash
      - id: ClothingEyesGlassesSecurity
      - id: ClothingEyesHudSecurity
      - id: ClothingHandsGlovesCombat
      - id: ClothingHeadsetSecurityWarden
      - id: ClothingShoesBootsJack
      - id: ClothingOuterCoatWarden
      - id: ClothingOuterWinterWarden
      - id: RubberStampWarden
      - id: DoorRemoteArmory
      - id: HoloprojectorSecurity
      - id: BookSpaceLaw
      - id: ClothingBackpackElectropack
        amount: 2
      - id: RemoteSignaller
        amount: 2
      - id: Binoculars

- type: entity
  id: LockerWardenLargeFHFilled
  suffix: NT, Filled
  parent: LockerWardenLargeFH
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        amount: 2
      - id: WeaponEnergyShotgun
      - id: WeaponDisabler
        amount: 2
      - id: ClothingBeltSecurityFilled
        amount: 2
      - id: Flash
        amount: 2
      - id: ClothingEyesGlassesSecurity
        amount: 2
      - id: ClothingEyesHudSecurity
        amount: 2
      - id: ClothingHandsGlovesCombat
        amount: 2
      - id: ClothingHeadsetSecurityWarden
        amount: 2
      - id: ClothingShoesBootsJack
        amount: 2
      - id: ClothingOuterCoatWarden
        amount: 2
      - id: ClothingOuterWinterWarden
        amount: 2
      - id: RubberStampWarden
        amount: 2
      - id: DoorRemoteArmory
        amount: 2
      - id: HoloprojectorSecurity
        amount: 2
      - id: BookSpaceLaw
        amount: 2
      - id: ClothingBackpackElectropack
        amount: 4
      - id: RemoteSignaller
        amount: 4
      - id: Binoculars
        amount: 2

- type: entity
  id: LockerBrigmedicLargeFHFilled
  suffix: NT, Filled
  parent: LockerBrigmedicLargeFH
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesBrigmedic
        amount: 2
      - id: ClothingEyesHudBrigmedic
        amount: 2
      - id: WeaponDisabler
        amount: 2
      - id: TrackingImplanter
        amount: 4
      - id: ClothingOuterHardsuitBrigmedic
        amount: 2
      - id: BoxSterileMask
      - id: ClothingHeadHatBeretBrigmedic
      - id: ClothingOuterCoatAMG
      - id: ClothingUniformJumpsuitBrigmedic
      - id: ClothingUniformJumpskirtBrigmedic
      - id: ClothingUniformJumpskirtOfLife
      - id: ClothingShoesBootsMagSec
        amount: 2
      - id: BedsheetBrigmedicStrange
      - id: BedsheetBrigmedic
      - id: SecurityMedkitFHFilledBrigmedic
        amount: 2
      - id: ClothingNeckCloakMoth #bzzz Moth-pocalypse
        prob: 0.35
      - id: RubberStampBrigmedic
        amount: 2

- type: entity
  id: LockerBrigmedicFHFilled
  suffix: NT, Filled
  parent: LockerBrigmedicFH
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesBrigmedic
      - id: ClothingEyesHudBrigmedic
      - id: WeaponDisabler
      - id: TrackingImplanter
        amount: 2
      - id: ClothingOuterHardsuitBrigmedic
      - id: BoxSterileMask
      - id: ClothingHeadHatBeretBrigmedic
      - id: ClothingOuterCoatAMG
      - id: ClothingUniformJumpsuitBrigmedic
      - id: ClothingUniformJumpskirtBrigmedic
      - id: ClothingUniformJumpskirtOfLife
      - id: ClothingShoesBootsMagSec
      - id: BedsheetBrigmedicStrange
      - id: PlasmaChemistryVial
      - id: BoxBeaker
      - id: BoxSyringe
      - id: DefibrillatorBrigmedical
      - id: SecurityMedkitFHFilledBrigmedic
      - id: ClothingNeckCloakMoth #bzzz Moth-pocalypse
        prob: 0.35
      - id: RubberStampBrigmedic

- type: entity
  id: LockerCorpsmanFilled
  suffix: NT, Filled
  parent: LockerCorpsman
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesCorpsman
      - id: ClothingEyesHudCorpsman
      - id: WeaponDisabler
      - id: TrackingImplanter
        amount: 2
      - id: ClothingOuterHardsuitCorpsman
      - id: BoxSterileMask
      - id: ClothingHeadHatBeretCorpsman
      - id: ClothingOuterCoatCorpsmanFH
      - id: ClothingUniformJumpsuitCorpsman
      - id: ClothingUniformJumpskirtCorpsman
      - id: ClothingBeltCorpsmanFilled
      - id: DefibrillatorCorpsman
      - id: SecurityHypoKitFilled
      - id: ClothingHandsGlovesBlackNitrile
      - id: ClothingShoesBootsMagSec
      - id: BedsheetCorpsmanStrange
      - id: SecurityMedkitFHFilledCorpsman
      - id: RubberStampCorpsman
      - id: PlushieMorgana
      - id: PlushieKiller

#region Syndicate









#region Security

# General Security

- type: entity
  id: LockerSecurityFHFilledSyndi
  suffix: Filled
  parent: LockerSecurityFHSyndi
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      - id: WeaponDisabler
      - id: ClothingUniformJumpsuitSecGreySyndi
        prob: 0.6
      - id: ClothingHeadHelmetSecuritySyndi
      - id: ClothingOuterArmorBasicSyndi
      - id: ClothingBeltSecuritySyndiFilled
      - id: Flash
      - id: ClothingEyesGlassesSecuritySyndi
      - id: ClothingEyesHudSecuritySyndi
      - id: ClothingHeadsetSecuritySyndi
      - id: ClothingHandsGlovesSecurityRed
      - id: ClothingShoesBootsJackSyndi
      - id: WeaponMeleeNeedle
      - id: HoloprojectorSecurity
      - id: BookSpaceLaw
  
- type: entity
  id: LockerSecurityLargeFHFilledSyndi
  suffix: Filled
  parent: LockerSecurityLargeFHSyndi
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        amount: 2
      - id: WeaponDisabler
        amount: 2
      - id: ClothingUniformJumpsuitSecGreySyndi
        prob: 0.6
      - id: ClothingHeadHelmetSecuritySyndi
        amount: 2
      - id: ClothingOuterArmorBasicSyndi
        amount: 2
      - id: ClothingBeltSecuritySyndiFilled
        amount: 2
      - id: Flash
        amount: 2
      - id: ClothingEyesGlassesSecuritySyndi
        amount: 2
      - id: ClothingEyesHudSecuritySyndi
        amount: 2
      - id: ClothingHeadsetSecuritySyndi
        amount: 2
      - id: ClothingHandsGlovesSecurityRed
        amount: 2
      - id: ClothingShoesBootsJackSyndi
        amount: 2
      - id: WeaponMeleeNeedle
      - id: HoloprojectorSecurity
        amount: 2
      - id: BookSpaceLaw
        amount: 2

- type: entity
  id: LockerSecurityLargeFHLFilledSyndi
  suffix: Filled, Left
  parent: LockerSecurityLargeFHLSyndi
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        amount: 2
      - id: WeaponDisabler
        amount: 2
      - id: ClothingUniformJumpsuitSecGreySyndi
        prob: 0.6
      - id: ClothingHeadHelmetSecuritySyndi
        amount: 2
      - id: ClothingOuterArmorBasicSyndi
        amount: 2
      - id: ClothingBeltSecuritySyndiFilled
        amount: 2
      - id: Flash
        amount: 2
      - id: ClothingEyesGlassesSecuritySyndi
        amount: 2
      - id: ClothingEyesHudSecuritySyndi
        amount: 2
      - id: ClothingHeadsetSecuritySyndi
        amount: 2
      - id: ClothingHandsGlovesSecurityRed
        amount: 2
      - id: ClothingShoesBootsJackSyndi
        amount: 2
      - id: WeaponMeleeNeedle
      - id: HoloprojectorSecurity
        amount: 2
      - id: BookSpaceLaw
        amount: 2

- type: entity
  id: LockerSecurityLargeFHMFilledSyndi
  suffix: Filled, Middle
  parent: LockerSecurityLargeFHMSyndi
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        amount: 3
      - id: WeaponDisabler
        amount: 3
      - id: ClothingUniformJumpsuitSecGreySyndi
        prob: 0.6
      - id: ClothingHeadHelmetSecuritySyndi
        amount: 3
      - id: ClothingOuterArmorBasicSyndi
        amount: 3
      - id: ClothingBeltSecuritySyndiFilled
        amount: 3
      - id: Flash
        amount: 3
      - id: ClothingEyesGlassesSecuritySyndi
        amount: 3
      - id: ClothingEyesHudSecuritySyndi
        amount: 3
      - id: ClothingHeadsetSecuritySyndi
        amount: 3
      - id: ClothingHandsGlovesSecurityRed
        amount: 3
      - id: ClothingShoesBootsJackSyndi
        amount: 3
      - id: WeaponMeleeNeedle
        amount: 2
      - id: HoloprojectorSecurity
        amount: 3
      - id: BookSpaceLaw
        amount: 3

- type: entity
  id: LockerSecurityLargeFHRFilledSyndi
  suffix: Filled, Right
  parent: LockerSecurityLargeFHRSyndi
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        amount: 2
      - id: WeaponDisabler
        amount: 2
      - id: ClothingUniformJumpsuitSecGreySyndi
        prob: 0.6
      - id: ClothingHeadHelmetSecuritySyndi
        amount: 2
      - id: ClothingOuterArmorBasicSyndi
        amount: 2
      - id: ClothingBeltSecuritySyndiFilled
        amount: 2
      - id: Flash
        amount: 2
      - id: ClothingEyesGlassesSecuritySyndi
        amount: 2
      - id: ClothingEyesHudSecuritySyndi
        amount: 2
      - id: ClothingHeadsetSecuritySyndi
        amount: 2
      - id: ClothingHandsGlovesSecurityRed
        amount: 2
      - id: ClothingShoesBootsJackSyndi
        amount: 2
      - id: WeaponMeleeNeedle
      - id: HoloprojectorSecurity
        amount: 2
      - id: BookSpaceLaw
        amount: 2

# Guardian (Warden)

- type: entityTable
  id: FillLockerGuardianHarduit
  table: !type:AllSelector
    children:
    - id: ClothingOuterHardsuitWardenSyndi
    - id: OxygenTankFilled
    - id: NitrogenTankFilled
    - id: ClothingMaskBreath

- type: entityTable
  id: FillLockerGuardian
  table: !type:AllSelector
    children:
    - id: WeaponEnergyShotgun
    - id: ClothingEyesHudSecuritySyndi
    - id: ClothingHeadsetSecurityWardenSyndi
    - id: FlashlightSeclite
    - id: WeaponDisabler
    - id: ClothingBeltSecuritySyndiFilled
    - id: Flash
    - id: ClothingEyesGlassesSecuritySyndi
    - id: ClothingHandsGlovesSecurityRed
    - id: ClothingShoesBootsJackSyndiFilled
    - id: ClothingOuterCoatWardenSyndi
    - id: ClothingOuterWinterWardenSyndi
    - id: RubberStampWarden
    - id: DoorRemoteArmory
    - id: HoloprojectorSecurity
    - id: BookSpaceLaw
    - id: ClothingBackpackElectropack
      amount: 2
    - id: RemoteSignaller
      amount: 2
    - id: NetworkConfigurator
    - id: Binoculars

- type: entity
  id: LockerGuardianFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerWardenFHSyndi
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:NestedSelector
          tableId: FillLockerGuardian
        - !type:NestedSelector
          tableId: FillLockerGuardianHarduit



# Medical Officer (Brigmedic)

- type: entity
  id: LockerBrigmedicLargeFHFilledSyndi
  suffix: Filled, Hardsuit
  parent: LockerBrigmedicLargeFHSyndi
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesBrigmedicSyndi
      - id: ClothingEyesHudBrigmedicSyndi
      - id: ClothingEyesEyepatchHudSecMedSyndi
      - id: ClothingEyesVisorSecMedSyndi
      - id: WeaponDisabler
        amount: 2
      - id: TrackingImplanter
        amount: 4
      - id: ClothingOuterHardsuitBrigmedicSyndi
        amount: 2
      - id: BoxSterileMask
      - id: ClothingHeadHatBeretMedicalOfficer
      #- id: ClothingOuterCoatAMG
      - id: ClothingUniformJumpsuitBrigmedicSyndi
      - id: ClothingUniformJumpskirtBrigmedicSyndi
      - id: ClothingShoesBootsMag
        amount: 2
      - id: BedsheetBrigmedicStrange
        prob: 0.6
      - id: BedsheetBrigmedic
      - id: SecurityMedkitFHFilledBrigmedic
        amount: 2
      - id: ClothingNeckCloakMoth #bzzz Moth-pocalypse
        prob: 0.35
      - id: RubberStampBrigmedic
        amount: 2

- type: entity
  id: LockerBrigmedicFHFilledSyndi
  suffix: Filled, Hardsuit
  parent: LockerBrigmedicFHSyndi
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesBrigmedicSyndi
      - id: ClothingEyesHudBrigmedicSyndi
      - id: ClothingEyesEyepatchHudSecMedSyndi
      - id: ClothingEyesVisorSecMedSyndi
      - id: WeaponDisabler
      - id: TrackingImplanter
        amount: 2
      - id: ClothingOuterHardsuitBrigmedicSyndi
      - id: BoxSterileMask
      - id: ClothingHeadHatBeretMedicalOfficer
      #- id: ClothingOuterCoatAMG
      - id: ClothingUniformJumpsuitBrigmedicSyndi
      - id: ClothingUniformJumpskirtBrigmedicSyndi
      #- id: ClothingUniformJumpskirtOfLife
      - id: ClothingShoesBootsMagSec
      - id: BedsheetBrigmedicStrange
        prob: 0.6
      - id: BedsheetBrigmedic
      - id: PlasmaChemistryVial
      - id: BoxBeaker
      - id: BoxSyringe
      - id: DefibrillatorBrigmedical
      - id: SecurityMedkitFHFilledBrigmedic
      - id: ClothingNeckCloakMoth #bzzz Moth-pocalypse
        prob: 0.35
      - id: RubberStampBrigmedic

# Combat Medic (Corpsman)

- type: entity
  id: LockerCorpsmanFilledSyndi
  suffix: Filled, Hardsuit
  parent: LockerCorpsmanFHSyndi
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesBrigmedicSyndi
      - id: ClothingEyesHudBrigmedicSyndi
      - id: ClothingEyesEyepatchHudSecMedSyndi
      - id: ClothingEyesVisorSecMedSyndi
      - id: WeaponDisabler
      - id: TrackingImplanter
        amount: 2
      - id: ClothingOuterHardsuitCorpsman
      - id: BoxSterileMask
      - id: ClothingHeadHatBeretCorpsman
      - id: ClothingOuterCoatCorpsmanFH
      - id: ClothingUniformJumpsuitCorpsman
      - id: ClothingUniformJumpskirtCorpsman
      - id: ClothingBeltCorpsmanFilled
      - id: DefibrillatorCorpsman
      - id: SecurityHypoKitFilled
      - id: ClothingHandsGlovesBlackNitrile
      - id: ClothingShoesBootsMagSec
      - id: BedsheetCorpsmanStrange
      - id: SecurityMedkitFHFilledCorpsman
      - id: RubberStampCorpsman
      - id: PlushieMorgana
      - id: PlushieKiller