using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._FarHorizons.UI.BackgroundTraits;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._FarHorizons.UI.BackgroundTraits;

[GenerateTypedNameReferences]
public sealed partial class BackgroundTraitsWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _protoMan = default!;
    [Dependency] private IResourceCache _resCache = default!;
    [Dependency] private IEntityManager _entityManager = default!;

    private List<ProtoId<BackgroundTraitPrototype>>? _availableTraits;
    private List<ProtoId<BackgroundTraitPrototype>> _selectedTraits = new();
    private EntityUid _entity;

    private static readonly Dictionary<int, string> _preloadCachePaths = new()
    {
        {1, "/Textures/_FarHorizons/Interface/Misc/number_icons/minus-1.png"},
        {2, "/Textures/_FarHorizons/Interface/Misc/number_icons/minus-2.png"},
        {3, "/Textures/_FarHorizons/Interface/Misc/number_icons/minus-3.png"},
        {4, "/Textures/_FarHorizons/Interface/Misc/number_icons/minus-4.png"},
        {5, "/Textures/_FarHorizons/Interface/Misc/number_icons/minus-5.png"},
        {6, "/Textures/_FarHorizons/Interface/Misc/number_icons/minus-6.png"},
        {7, "/Textures/_FarHorizons/Interface/Misc/number_icons/minus-7.png"},
        {8, "/Textures/_FarHorizons/Interface/Misc/number_icons/minus-8.png"},
        {9, "/Textures/_FarHorizons/Interface/Misc/number_icons/minus-9.png"},
        {-1, "/Textures/_FarHorizons/Interface/Misc/number_icons/plus-1.png"},
        {-2, "/Textures/_FarHorizons/Interface/Misc/number_icons/plus-2.png"},
        {-3, "/Textures/_FarHorizons/Interface/Misc/number_icons/plus-3.png"},
        {-4, "/Textures/_FarHorizons/Interface/Misc/number_icons/plus-4.png"},
        {-5, "/Textures/_FarHorizons/Interface/Misc/number_icons/plus-5.png"},
        {-6, "/Textures/_FarHorizons/Interface/Misc/number_icons/plus-6.png"},
        {-7, "/Textures/_FarHorizons/Interface/Misc/number_icons/plus-7.png"},
        {-8, "/Textures/_FarHorizons/Interface/Misc/number_icons/plus-8.png"},
        {-9, "/Textures/_FarHorizons/Interface/Misc/number_icons/plus-9.png"},
    };

    private readonly Dictionary<int, Texture> _textureCache;

    public Action<List<ProtoId<BackgroundTraitPrototype>>>? SelectTraitsCallback;

    public BackgroundTraitsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _textureCache = PreloadCache();

        PositiveTraits.OnItemSelected += PositiveSelected;
        PositiveTraits.OnItemDeselected += PositiveDeselected;
        NegativeTraits.OnItemSelected += NegativeSelected;
        NegativeTraits.OnItemDeselected += NegativeDeselected;
        SelectedTraits.OnItemSelected += SelectedSelected;
        SelectedTraits.OnItemDeselected += SelectedDeselected;

        PositiveTraitAdd.OnPressed += AddSelectedPositiveTrait;
        NegativeTraitAdd.OnPressed += AddSelectedNegativeTrait;
        TraitRemove.OnPressed += RemoveSelectedTrait;

        SubmitButton.OnPressed += SubmitButtonPressed;
    }

    public void OnStart(EntityUid entity)
    {
        _entity = entity;

        if(!_entityManager.TryGetComponent<BackgroundTraitsComponent>(_entity, out var traitsComp))
            return;
        
        _availableTraits = traitsComp.Traits;
        Title = Loc.GetString(traitsComp.WindowName);

        GenerateLists();
        RefreshButtons();
        UpdatePointsDisplay();
        UpdateInfo();
    }

    private Dictionary<int, Texture> PreloadCache()
    {
        var output = new Dictionary<int, Texture>();

        foreach (var (k, path) in _preloadCachePaths)
            output.Add(k, _resCache.GetResource<TextureResource>(path).Texture);

        return output;
    }

    private void PositiveSelected(ItemList.ItemListSelectedEventArgs args)
    {
        NegativeTraits.ClearSelected();
        SelectedTraits.ClearSelected();

        PositiveTraitAdd.Disabled = false;
        UpdateInfo();
    }

    private void PositiveDeselected(ItemList.ItemListDeselectedEventArgs args)
    {
        PositiveTraitAdd.Disabled = true;
        UpdateInfo();
    }

    private void NegativeSelected(ItemList.ItemListSelectedEventArgs args)
    {
        PositiveTraits.ClearSelected();
        SelectedTraits.ClearSelected();

        NegativeTraitAdd.Disabled = false;
        UpdateInfo();
    }

    private void NegativeDeselected(ItemList.ItemListDeselectedEventArgs args)
    {
        NegativeTraitAdd.Disabled = true;
        UpdateInfo();
    }

    private void SelectedSelected(ItemList.ItemListSelectedEventArgs args)
    {
        PositiveTraits.ClearSelected();
        NegativeTraits.ClearSelected();

        TraitRemove.Disabled = false;
        UpdateInfo();
    }

    private void SelectedDeselected(ItemList.ItemListDeselectedEventArgs args)
    {
        TraitRemove.Disabled = true;
        UpdateInfo();
    }

    private void SubmitButtonPressed(BaseButton.ButtonEventArgs args)
    {
        SubmitButton.Disabled = true;
        SelectTraitsCallback?.Invoke(_selectedTraits);
    }

    private void AddSelectedPositiveTrait(BaseButton.ButtonEventArgs args)
    {
        var allSelected = PositiveTraits.GetSelected();
        if (allSelected.FirstOrDefault() is not { } selected ||
            selected.Metadata is not BackgroundTraitPrototype trait ||
            !IsCompatible(trait))
            return;

        _selectedTraits.Add(trait.ID);
        GenerateLists();
        RefreshButtons();
        UpdatePointsDisplay();
        UpdateInfo();
    }

    private void AddSelectedNegativeTrait(BaseButton.ButtonEventArgs args)
    {
        var allSelected = NegativeTraits.GetSelected();
        if (allSelected.FirstOrDefault() is not { } selected ||
            selected.Metadata is not BackgroundTraitPrototype trait ||
            !IsCompatible(trait))
            return;

        _selectedTraits.Add(trait.ID);
        GenerateLists();
        RefreshButtons();
        UpdatePointsDisplay();
        UpdateInfo();
    }

    private void RemoveSelectedTrait(BaseButton.ButtonEventArgs args)
    {
        var allSelected = SelectedTraits.GetSelected();
        if (allSelected.FirstOrDefault() is not { } selected ||
            selected.Metadata is not BackgroundTraitPrototype trait)
            return;

        _selectedTraits.Remove(trait.ID);
        GenerateLists();
        RefreshButtons();
        UpdatePointsDisplay();
        UpdateInfo();
    }

    private void GenerateLists()
    {
        if(_availableTraits == null) return;
        
        var resolved = _availableTraits.Select(id => _protoMan.Index(id)).ToList();

        var selectedTraits = resolved.Where(p => _selectedTraits.Contains(p.ID))
            .OrderByDescending(p => p.Cost).ThenBy(p => p.ID).ToList();
        var notSelectedTraits = resolved.Where(p => !_selectedTraits.Contains(p.ID)).ToList();
        var positiveTraits = notSelectedTraits.Where(p => p.Cost >= 0)
            .OrderBy(p => p.Cost).ThenBy(p => p.ID).ToList();
        var negativeTraits = notSelectedTraits.Where(p => p.Cost < 0)
            .OrderByDescending(p => p.Cost).ThenBy(p => p.ID).ToList();

        PositiveTraits.Clear();
        foreach (var trait in positiveTraits)
        {
            var item = PositiveTraits.AddItem(Loc.GetString(trait.Name), metadata: trait, iconScale: 0.6f);
            item.Disabled = !IsCompatible(trait);
            if (_textureCache.TryGetValue(trait.Cost, out var texture))
                item.Icon = texture;
        }

        NegativeTraits.Clear();
        foreach (var trait in negativeTraits)
        {
            var item = NegativeTraits.AddItem(Loc.GetString(trait.Name), metadata: trait, iconScale: 0.6f);
            item.Disabled = !IsCompatible(trait);
            if (_textureCache.TryGetValue(trait.Cost, out var texture))
                item.Icon = texture;
        }

        SelectedTraits.Clear();
        foreach (var trait in selectedTraits)
        {
            var item = SelectedTraits.AddItem(Loc.GetString(trait.Name), metadata: trait, iconScale: 0.6f);
            if (_textureCache.TryGetValue(trait.Cost, out var texture))
                item.Icon = texture;
        }
    }

    private void RefreshButtons()
    {
        PositiveTraitAdd.Disabled = !PositiveTraits.GetSelected().Any();
        NegativeTraitAdd.Disabled = !NegativeTraits.GetSelected().Any();
        TraitRemove.Disabled = !SelectedTraits.GetSelected().Any();
        SubmitButton.Disabled = GetCurrentPoints() < 0;
    }

    private int GetCurrentPoints()
    {
        if (_availableTraits == null) return 0;
        return _selectedTraits
            .Select(id => _protoMan.Index(id))
            .Aggregate(0, (current, trait) => current - trait.Cost);
    }

    private void UpdatePointsDisplay() =>
        TotalPointsLabel.Text = Loc.GetString("lesser-vampire-ui-menu-points-label", ("value", GetCurrentPoints()));

    private bool IsCompatible(ProtoId<BackgroundTraitPrototype> target)
    {
        var proto = _protoMan.Index(target);
        return IsCompatible(proto);
    }

    private bool IsCompatible(BackgroundTraitPrototype target) =>
        !_selectedTraits.Intersect(target.Incompatible).Any();

    private BackgroundTraitPrototype? GetCurrentSelected()
    {
        var selected = PositiveTraits.GetSelected().ToList();
        selected.AddRange(NegativeTraits.GetSelected());
        selected.AddRange(SelectedTraits.GetSelected());

        var selectedProtos = selected.Select(p => p.Metadata as BackgroundTraitPrototype).ToList();

        if (selectedProtos.Count != 1) return null;
        return selectedProtos.First();
    }

    private void UpdateInfo()
    {
        if (_availableTraits == null) return;

        DescriptionSelectionName.Text = "";
        DescriptionSelectionCost.Text = "";
        DescriptionSelectionDescription.Text = "";
        DescriptionSelectionIncompatible.Text = "";

        var selected = GetCurrentSelected();
        if (selected == null) return;

        DescriptionSelectionName.Text =
            Loc.GetString("lesser-vampire-ui-menu-info-name", ("value", Loc.GetString(selected.Name)));
        DescriptionSelectionCost.Text = Loc.GetString("lesser-vampire-ui-menu-info-cost", ("value", selected.Cost));
        DescriptionSelectionDescription.Text = Loc.GetString("lesser-vampire-ui-menu-info-description",
            ("value", Loc.GetString(selected.Description)));

        if (selected.Incompatible.Count == 0) return;

        var incompatibilities = "";
        foreach (var other in _availableTraits.Select(id => _protoMan.Index(id)).Where(p => selected.Incompatible.Contains(p.ID)))        
        {
            incompatibilities += '\n';
            incompatibilities += Loc.GetString("lesser-vampire-ui-menu-info-incompatible-item",
                ("value", Loc.GetString(other.Name)));
        }
        DescriptionSelectionIncompatible.Text =
            Loc.GetString("lesser-vampire-ui-menu-info-incompatible", ("value", incompatibilities));
    }
}